services:
  backend:
    container_name: visualizer_backend
    image: visualizer_backend:1.0.0
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '4000:4000'
    restart: always
    volumes:
      - ./backend:/code
    command: ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "4000", "--reload"]